server:
  port: 7000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
    gateway:
      discovery:
        locator:
          #让gateway可以从nacos发现服务
          enabled: true